const allProperties = [
  {
    id: 1,
    title: "Modern Townhouse",
    type: "terraceDuplex",
    location: "Abraham Adesanya",
    region: "Lagos",
    category: "residential",
    price: 300000000,
    beds: 5,
    baths: 6,
    sqft: 2100,
    cover_image: "images/listing1.jpg",
  },
  {
    id: 2,
    title: "Spanish Colonial Estate",
    type: "detachedDuplex",
    location: "Ikeja",
    region: "Lagos",
    category: "commercial",
    price: 500000000,
    beds: 7,
    baths: 7,
    sqft: 3200,
    cover_image: "images/listing2.jpg",
  },
  {
    id: 3,
    title: "Luxury Landed Property",
    type: "land",
    location: "Ibeju Lekki",
    region: "Lagos",
    category: "residential",
    price: 45000000,
    beds: 0,
    baths: 0,
    sqft: 12000,
    cover_image: "images/land-listing.jpg",
  },
  {
    id: 4,
    title: "Waterfront Penthouse",
    type: "bungalow",
    location: "Ikoyi",
    region: "Lagos",
    category: "commercial",
    price: 380000000,
    beds: 4,
    baths: 4,
    sqft: 2500,
    cover_image: "images/listing3.jpg",
  },
  {
    id: 5,
    title: "Modern Luxury Estate",
    type: "apartment",
    location: "Chevron Estate",
    region: "Lagos",
    category: "residential",
    price: 35000000,
    beds: 6,
    baths: 6,
    sqft: 4200,
    cover_image: "images/listing4.jpg",
  },
  {
    id: 6,
    title: "Contemporary Family Home",
    type: "detachedDuplex",
    location: "Ajah",
    region: "Lagos",
    category: "residential",
    price: 45000000,
    beds: 4,
    baths: 5,
    sqft: 2000,
    cover_image: "images/listing5.jpg",
  },
  {
    id: 7,
    title: "Mediterranean Villa",
    type: "bungalow",
    location: "Ibeju Lekki",
    region: "Lagos",
    category: "residential",
    price: 50000000,
    beds: 4,
    baths: 6,
    sqft: 2000,
    cover_image: "images/listing6.jpg",
  },
  {
    id: 8,
    title: "Palm Jumeirah Penthouse",
    type: "terraceDuplex",
    location: "Banana Island",
    region: "Lagos",
    category: "residential",
    price: 850000000,
    beds: 8,
    baths: 8,
    sqft: 3000,
    cover_image: "images/listing7.jpg",
  },
  {
    id: 9,
    title: "Mid-Century Modern Gem",
    type: "apartment",
    location: "Ibeju Lekki",
    region: "Lagos",
    category: "residential",
    price: 50000000,
    beds: 5,
    baths: 6,
    sqft: 2850,
    cover_image: "images/listing8.jpg",
  },
];
